version: "3.0"

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.2
    container_name: dcoker-zookeeper
    restart: always
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
      ZOOKEEPER_SERVERS: "zookeeper:22888:23888"
    ports:
      - "2181:2181"
                  
  kafka1:
    image: confluentinc/cp-kafka:5.4.2
    container_name: dcoker-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,EXTERNAL://localhost:29092
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: "r1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_SCHEMA_REGISTRY_URL: "schemaregistry:8085"
      KAFKA_LOG4J_LOGGERS: "kafka.controller=WARN,kafka.foo.bar=DEBUG"
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
      KAFKA_JMX_PORT: 9991
      
      
  schemaregistry:
    image: confluentinc/cp-schema-registry:5.4.2
    container_name: dcoker-schemaregistry
    restart: always
    depends_on:
      - zookeeper
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8085"
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: GET,POST,PUT,OPTIONS
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
      SCHEMA_REGISTRY_LOG4J_LOGGERS: "kafka.controller=WARN,kafka.foo.bar=DEBUG"
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: WARN
      SCHEMA_REGISTRY_TOOLS_LOG4J_LOGLEVEL: ERROR
    ports:
      - 8085:8085

  notificationservice:
    container_name: dcoker-notification
    build: .
    depends_on:
      - kafka1
      - schemaregistry
    environment:
      PORT: 7070
      KAFKA_BOOTSTRAP_SERVER: "kafka1:9092"
      TOPIC: "primary-topic-notification"
      TOPIC_DLQ: "dlq-topic-notification"
      CLIENT_ID: "notification-user"
      CLIENT_ID_DLQ: "dlq-notification-user"
      ALARM_EMAIL: "email to get alarm"
      SCHEMA_REGISTRY_URL: "http://schemaregistry:8085"
    ports:
      - '7070:7070'  





